meta_product_name: "Concert Match"
meta_title: "Concert Match - Discover your music community, one concert at a time"
meta_description: "Discover your music community, one concert at a time"
meta_image: "coverconcert.jpg" # should exist in `app/assets/images/`
